--
-- VHDL Architecture Beamer.beamerPeriphOperator.empty
--
-- Created:
--          by - francois.UNKNOWN (WE3673)
--          at - 16:45:59 20.01.2012
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ARCHITECTURE empty OF beamerPeriphOperator IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- Instance port mappings.

END empty;
